language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules 
services:
  - postgresql
before_script:
  - psql -c 'create database elevate;' -U postgres
  - psql < backend/data.sql
  - for i in *; do first=$(echo "${i:0:1}" | tr '[:upper:]' '[:lower:]'); new=$first${i:1}; mv "$i" "$new"; done

env:
  - TEST_DIR=frontend
  - TEST_DIR=backend
script: cd $TEST_DIR && npm install && npm test
