language: node_js
node_js:
  - '10'
services:
  - postgresql
before_script:
  - psql -c 'create database elevate;' -U postgres
  - psql < backend/data.sql
before_install:
- npm update
install:
- npm --prefix ./backend install ./
- npm install --save-dev jest
script:
- jest backend --runInBand --silent