language: node_js
node_js:
  - '10'
services:
  - postgresql
before_script:
  - psql -c 'create database elevate;' -U postgres
  - psql < backend/data.sql
env:
  - TEST_DIR=frontend
  - TEST_DIR=backend
script: cd $TEST_DIR && npm install && npm test
