language: node_js
node_js:
  - '10'
services:
  - postgresql
before_script:
  - psql -c 'create database elevate;' -U postgres
  - psql < backend/data.sql
before_install:
- npm update
script:
- cd backend
- npm install  
- npm install --save-dev jest
- npm test